name: Continuous Integration

on:
  push:
    branches:
      - dev
    paths:
      - 'pdf/**'

permissions: write-all

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de que suas dependências estão listadas no arquivo

      - name: Run populate_database
        run: python populate_database.py
